// src/components/react/Counter.tsx
/** @jsxImportSource react */
import { useState } from "react";

interface CounterProps {
	start?: number;
}

export default function Counter({ start = 0 }: CounterProps) {
	const [count, setCount] = useState(start);

	return (
		<div className="card border border-base-300 bg-base-100 shadow-md">
			<div className="card-body items-center gap-4 text-center">
				<span className="badge badge-info">React</span>
				<p className="text-4xl font-bold tabular-nums">{count}</p>
				<div className="join">
					<button
						type="button"
						className="btn join-item"
						onClick={() => setCount((c) => c - 1)}
					>
						-
					</button>
					<button
						type="button"
						className="btn join-item"
						onClick={() => setCount((c) => c + 1)}
					>
						+
					</button>
				</div>
			</div>
		</div>
	);
}

// src/components/solid/Counter.tsx
import { createSignal } from "solid-js";

interface CounterProps {
	start?: number;
}

export default function Counter(props: CounterProps) {
	const [count, setCount] = createSignal(props.start ?? 0);

	return (
		<div class="card border border-base-300 bg-base-100 shadow-md">
			<div class="card-body items-center gap-4 text-center">
				<span class="badge badge-success">Solid</span>
				<p class="text-4xl font-bold tabular-nums">{count()}</p>
				<div class="join">
					<button
						type="button"
						class="btn join-item"
						onClick={() => setCount(count() - 1)}
					>
						-
					</button>
					<button
						type="button"
						class="btn join-item"
						onClick={() => setCount(count() + 1)}
					>
						+
					</button>
				</div>
			</div>
		</div>
	);
}
